[2024-04-15 12:15:35,518][root][INFO] - Command line args:

[2024-04-15 12:15:35,518][root][INFO] - Hydra and wandb output path: /Users/ajgeorge/python/sis/logs/2024-04-15/12-15-35
[2024-04-15 12:15:35,518][root][INFO] - Solver output path: /Users/ajgeorge/python/sis/logs/2024-04-15/12-15-35
[2024-04-15 12:15:43,024][root][INFO] - ---------------------------------------------------------------
[2024-04-15 12:15:43,027][root][INFO] - Run config:
wandb:
  project: sis
  resume: allow
  mode: run
  name: 2024-04-15/12-15-35,
  tags: []
  id: 977854c8c2df2ad1644aed5818100d6983dfbc1c9081ff253f46bfdc0fdbf442
keops_build_path: /Users/ajgeorge/.cache/keops/unknown/2024-04-15/12-15-35
merge_wandb_resume_cfg: true
restore_ckpt_from_wandb: true
target:
  _target_: stint_sampler.targets.targets.gmm
  mean: 5.0
  var: 1.0
interpolant:
  _target_: stint_sampler.stint.linearInterpolants.linear
  type: sin
model:
  _target_: stint_sampler.models.scoreNets.DenseNet
  dim: 2
  features:
  - 20
  - 50
  - 200
  - 200
  - 50
seed: 1
T: 1.0
dim: 2
eps0: 1.0e-05
eps1: 1.0e-05
batch_size: 128
log_interval: 10
eval_interval: 200
train:
  NtTrain: 50
  epochs: 1000
  epoch_steps: 4
  learning_rate: 0.01
solver:
  _target_: stint_sampler.stint.sis.half_sis
sampler:
  Nsamples: 10000
  NtSampler: 1000
eval:
  hist_dims:
  - 0
  - 1
out_dir: /Users/ajgeorge/python/sis/logs/2024-04-15/12-15-35

[2024-04-15 12:15:43,027][root][INFO] - ---------------------------------------------------------------
[2024-04-15 12:15:43,983][jax._src.xla_bridge][INFO] - Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
[2024-04-15 12:15:43,983][jax._src.xla_bridge][INFO] - Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
[2024-04-15 12:15:43,985][jax._src.xla_bridge][INFO] - Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: dlopen(libtpu.so, 0x0001): tried: 'libtpu.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibtpu.so' (no such file), '/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/jaxlib/../../../libtpu.so' (no such file), '/Users/ajgeorge/anaconda3/envs/sis/bin/../lib/libtpu.so' (no such file), '/usr/lib/libtpu.so' (no such file, not in dyld cache), 'libtpu.so' (no such file), '/usr/local/lib/libtpu.so' (no such file), '/usr/lib/libtpu.so' (no such file, not in dyld cache)
[2024-04-15 12:15:44,109][root][INFO] - Checkpoint directory: /Users/ajgeorge/python/sis/logs/2024-04-15/12-15-35/ckpt
[2024-04-15 12:19:54,017][root][INFO] - Completed âœ…
