[2024-04-16 14:35:28,872][root][INFO] - Command line args:

[2024-04-16 14:35:28,872][root][INFO] - Hydra and wandb output path: /Users/ajgeorge/python/sis/logs/2024-04-16/14-35-28
[2024-04-16 14:35:28,873][root][INFO] - Solver output path: /Users/ajgeorge/python/sis/logs/2024-04-16/14-35-28
[2024-04-16 14:35:36,370][root][INFO] - ---------------------------------------------------------------
[2024-04-16 14:35:36,378][root][INFO] - Run config:
wandb:
  project: sis
  resume: allow
  mode: run
  name: 2024-04-16/14-35-28,
  tags: []
  id: c739bdfe2a478178891bd1b41f82381a372c9fa0a44396705e04c4c46d351e1f
keops_build_path: /Users/ajgeorge/.cache/keops/unknown/2024-04-16/14-35-28
merge_wandb_resume_cfg: true
restore_ckpt_from_wandb: true
target:
  _target_: stint_sampler.targets.targets.gmm
  d: 2
  mean: 5.0
  var: 1.0
interpolant:
  _target_: stint_sampler.stint.linearInterpolants.linear
  type: trig
model:
  _target_: stint_sampler.models.energyNets.DenseNet
  features:
  - 20
  - 50
  - 200
  - 200
  - 50
  - 1
hjb_solver:
  _target_: stint_sampler.hjb_solver.fbsde.fbsde
seed: 1
T: 1.0
dim: 2
eps0: 1.0e-05
eps1: 1.0e-05
batch_size: 128
log_interval: 10
eval_interval: 100
jit_lossFn: 0
train:
  NtTrain: 100
  epochs: 2000
  epoch_steps: 4
  learning_rate: 0.01
solver:
  _target_: stint_sampler.stint.sis.half_sis
sampler:
  Nsamples: 10000
  NtSampler: 1000
eval:
  hist_dims:
  - 0
  - 1
out_dir: /Users/ajgeorge/python/sis/logs/2024-04-16/14-35-28

[2024-04-16 14:35:36,379][root][INFO] - ---------------------------------------------------------------
[2024-04-16 14:35:37,005][jax._src.xla_bridge][INFO] - Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
[2024-04-16 14:35:37,006][jax._src.xla_bridge][INFO] - Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
[2024-04-16 14:35:37,009][jax._src.xla_bridge][INFO] - Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: dlopen(libtpu.so, 0x0001): tried: 'libtpu.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibtpu.so' (no such file), '/Users/ajgeorge/anaconda3/envs/sis/lib/python3.11/site-packages/jaxlib/../../../libtpu.so' (no such file), '/Users/ajgeorge/anaconda3/envs/sis/bin/../lib/libtpu.so' (no such file), '/usr/lib/libtpu.so' (no such file, not in dyld cache), 'libtpu.so' (no such file), '/usr/local/lib/libtpu.so' (no such file), '/usr/lib/libtpu.so' (no such file, not in dyld cache)
[2024-04-16 14:35:37,150][root][INFO] - Checkpoint directory: /Users/ajgeorge/python/sis/logs/2024-04-16/14-35-28/ckpt
